### PR TITLE
FUL-4153: Hide password strength label on small screens

### PR DESCRIPTION
**Pull request by Waboodoo**

### CODE REVIEW

**Comment by Waboodoo** [comment]
@Waboodoo assigned @Wattos and added the label **Reviewer Attention Required**.

**Comment by Wattos** [comment]
Looks good to me. Thanks Roland!

**Comment by Wattos** [comment]
@Wattos removed the label **Reviewer Attention Required** and added the label **Approved**

**Comment by Waboodoo** [comment]
@Wattos You have the honor of merging this, as I lack the permission to do so.

**Pull request merged**
